### ISSUE TITLE
 picker.setSelectedItem(2017,10,24,13,22);  it seems like the hour and minute donest work

### ISSUE THREAD

**Issue by LukeMi** [addappcn/android-pickers#10]
DateTimePicker picker = new DateTimePicker(this,DateTimePicker.YEAR_MONTH_DAY, DateTimePicker.HOUR_24);
        picker.setDateRangeStart(2017, 1, 1);
        picker.setDateRangeEnd(2025, 11, 11);
        picker.setSelectedItem(2017,10,24,13,22);
        picker.setTimeRangeStart(0, 0);
        picker.setTimeRangeEnd(23, 59);
        picker.setWeightEnable(true);
        picker.setWheelModeEnable(true);
        picker.setOnDateTimePickListener(new DateTimePicker.OnYearMonthDayTimePickListener() {
            @Override
            public void onDateTimePicked(String year, String month, String day, String hour, String minute) {
                showToast(year + "-" + month + "-" + day + " " + hour + ":" + minute);
            }
        });
        picker.show(); 

 the result show 2017-10-24 00:00  not 2017-10-24 13:22

**Comment by fantasyowen** [comment]
是的，确实存在这个问题。

**Comment by fantasyowen** [comment]
have you resolve it？

**Comment by LukeMi** [comment]
no , i have to use other library,   this for reference compile 'com.contrarywind:Android-PickerView:3.2.6'

**Comment by addappcn** [comment]
已解决，代码过几天提交。
