### ISSUE TITLE
建议把SinglePicker的formatToString方法设置成继承可修改的方法。

### ISSUE THREAD

**Issue by w0080626** [addappcn/android-pickers#18]
既然SinglePicker可以设置泛型数据，希望可以放开formatToString的方法，让开发者自己实现，这样的话什么样子的数据都可以设置进去了。希望作者采纳！

**Comment by w0080626** [comment]
因为项目着急，所以只能把SinglePicker copy了一份，把formatToString的修饰符改成了protected就完美实现了。 希望作者采纳！ 感谢

**Comment by addappcn** [comment]
ok，已改。
