### ISSUE TITLE
点击弹窗区域外不消失  能否提供一个方法  自己去选择消不消失

### ISSUE THREAD

**Issue by jason609** [addappcn/android-pickers#24]
点击弹窗区域外不消失  能否提供一个方法  自己去选择消不消失

**Comment by addappcn** [comment]
请具体描述问题

**Comment by jason609** [comment]
点击弹窗外区域，弹窗不消失，看源码  是你在创建弹窗时 直接设置setOutsideTouchable(true)，能否把这个方法让调用者自己设置

**Comment by LOWANGA** [comment]
这个不能设置只能改源码 比较难受

**Comment by mailiang1995** [comment]
你好，在BaseDialog类中增加一个方法即可：
    public void setCanceledOnTouchOutside(boolean canceled){
        if (canceled){
            dialog.setCancelable(true);
            dialog.setCanceledOnTouchOutside(true);
        }
    }
调用picker.setCanceledOnTouchOutside(true);可实现该功能

**Comment by huang0228** [comment]
thanks，try later

**Comment by addappcn** [comment]
不好意思，前段时间有事，现在才修改。加上去了
