### ISSUE TITLE
DateTimePickers的setSelectedItem传值为0时，报错

### ISSUE THREAD

**Issue by ccMagic** [addappcn/android-pickers#26]
`  

     // picker.setSelectedItem(calendar.get(Calendar.YEAR),
    //calendar.get(Calendar.MONTH)+1,
    // calendar.get(Calendar.DAY_OF_MONTH),
    //calendar.get(Calendar.HOUR_OF_DAY),
    // calendar.get(Calendar.MINUTE));

      picker.setSelectedItem(calendar.get(Calendar.YEAR),
      calendar.get(Calendar.MONTH)+1,
      calendar.get(Calendar.DAY_OF_MONTH),
      0,
      0);

`

java.lang.NumberFormatException
Invalid int: "
1 java.lang.Integer.invalidInt(Integer.java:138)
--
2 java.lang.Integer.parseInt(Integer.java:358)
3 java.lang.Integer.parseInt(Integer.java:334)
4 cn.addapp.pickers.picker.DateTimePicker$11.compare(DateTimePicker.java:842)
5 java.util.Collections.binarySearch(Collections.java:1497)
6 cn.addapp.pickers.picker.DateTimePicker.findItemIndex(DateTimePicker.java:835)
7 cn.addapp.pickers.picker.DateTimePicker.setSelectedItem(DateTimePicker.java:285)

**Comment by Drawn0-0** [comment]
解决办法： 在DateTimerPicker类中 的 findItemIndex 方法对 rhsStr进行判断 处理，具体 代码：

```
    private int findItemIndex(ArrayList<String> items, int item) {
        //折半查找有序元素的索引
        int index = Collections.binarySearch(items, item, new Comparator<Object>() {
            @Override
            public int compare(Object lhs, Object rhs) {
                String lhsStr = lhs.toString();
                String rhsStr = rhs.toString();
                //添加这一句
                rhsStr = rhsStr.equals("0")?"00":rhsStr;
                lhsStr = lhsStr.startsWith("0") ? lhsStr.substring(1) : lhsStr;
                rhsStr = rhsStr.startsWith("0") ? rhsStr.substring(1) : rhsStr;
                return Integer.parseInt(lhsStr) - Integer.parseInt(rhsStr);
            }
        });
        if (index < 0) {
            throw new IllegalArgumentException("Item[" + item + "] out of range");
        }
        return index;
    }
```

**Comment by ccMagic** [comment]
`  private int findItemIndex(ArrayList<String> items, int item) {
        //折半查找有序元素的索引
        int index = Collections.binarySearch(items, item, new Comparator<Object>() {
            @Override
            public int compare(Object lhs, Object rhs) {
                String lhsStr = lhs.toString();
                String rhsStr = rhs.toString();
                lhsStr = lhsStr.equals("0") ? lhsStr : lhsStr.startsWith("0") ? lhsStr.substring(1) : lhsStr;
                rhsStr = rhsStr.equals("0") ? rhsStr : rhsStr.startsWith("0") ? rhsStr.substring(1) : rhsStr;
                return Integer.parseInt(lhsStr) - Integer.parseInt(rhsStr);
            }
        });
        if (index < 0) {
            throw new IllegalArgumentException("Item[" + item + "] out of range");
        }
        return index;
    }`

**Comment by ccMagic** [comment]
private int findItemIndex(ArrayList<String> items, int item) {
        //折半查找有序元素的索引
        int index = Collections.binarySearch(items, item, new Comparator<Object>() {
            @Override
            public int compare(Object lhs, Object rhs) {
                String lhsStr = lhs.toString();
                String rhsStr = rhs.toString();
                lhsStr = lhsStr.equals("0") ? lhsStr : lhsStr.startsWith("0") ? lhsStr.substring(1) : lhsStr;
                rhsStr = rhsStr.equals("0") ? rhsStr : rhsStr.startsWith("0") ? rhsStr.substring(1) : rhsStr;
                return Integer.parseInt(lhsStr) - Integer.parseInt(rhsStr);
            }
        });
        if (index < 0) {
            throw new IllegalArgumentException("Item[" + item + "] out of range");
        }
        return index;
    }

**Comment by ccMagic** [comment]
```
  private int findItemIndex(ArrayList<String> items, int item) {
        //折半查找有序元素的索引
        int index = Collections.binarySearch(items, item, new Comparator<Object>() {
            @Override
            public int compare(Object lhs, Object rhs) {
                String lhsStr = lhs.toString();
                String rhsStr = rhs.toString();
                lhsStr = lhsStr.equals("0") ? lhsStr : lhsStr.startsWith("0") ? lhsStr.substring(1) : lhsStr;
                rhsStr = rhsStr.equals("0") ? rhsStr : rhsStr.startsWith("0") ? rhsStr.substring(1) : rhsStr;
                return Integer.parseInt(lhsStr) - Integer.parseInt(rhsStr);
            }
        });
        if (index < 0) {
            throw new IllegalArgumentException("Item[" + item + "] out of range");
        }
        return index;
    }
```

**Comment by addappcn** [comment]
String lhsStr = lhs.toString().equals("0") ? "00" : lhs.toString();
                String rhsStr = rhs.toString().equals("0") ? "00" : rhs.toString();
                lhsStr = lhsStr.startsWith("0") ? lhsStr.substring(1) : lhsStr;
                rhsStr = rhsStr.startsWith("0") ? rhsStr.substring(1) : rhsStr;
                try {
                    return Integer.parseInt(lhsStr) - Integer.parseInt(rhsStr);
                } catch (java.lang.NumberFormatException e) {
                    e.printStackTrace();
                    return 0;
                }
