### ISSUE TITLE
DateTimePicker使用setDateRangeStart()方法设置起始日期有bug

### ISSUE THREAD

**Issue by xiaodxs** [addappcn/android-pickers#27]
当我设置其实日期为 setDateRangeStart(2018,9,1)后,我的月份选择只出现 9,10,11,12四个月份,并且当我切换到其他的 年份的时候 月份选择 一直只有 9,10,11,12 这4个选项

**Comment by addappcn** [comment]
你查看下的么有问题吗 ，你在试试还有问题没有。
