### ISSUE TITLE
比如当选择起始时间为2018-10-21 不管你后面怎么选择其他年份，月份都只有10 11 12月，这问题有点大啊

### ISSUE THREAD

**Issue by MZCretin** [addappcn/android-pickers#28]

**Comment by ncworm** [comment]
遇到同样的问题。setRangeStart     setRangeEnd  这两个是有问题的

**Comment by addappcn** [comment]
没有问题啊 就是这样设计的 你设置从10月份开始 难道还能选择10月之前的吗？

**Comment by MZCretin** [comment]
@addappcn   那我年份换成2017 不应该显示1~12月吗？也还是只有10 11 12月

**Comment by FinleyLC** [comment]
设置2019年10月开始，那么如果滑动到2020年，月份还是不变。。。只能选10,11,12月

**Comment by FinleyLC** [comment]
我知道了。。看了下源码要setCanLinkage(true);才行，不然年不会联动月

**Comment by addappcn** [comment]
嗯是的 只有你设置联动 才会联动
