### ISSUE TITLE
关于时分秒选择问题

### ISSUE THREAD

**Issue by LiuFreedom** [addappcn/android-pickers#3]
很抱歉之前未能及时回复
![screenshot_2017-05-18-08-44-24 1](https://cloud.githubusercontent.com/assets/12256227/26182072/df6be7f6-3ba7-11e7-87ff-f7ccdf3fe3e5.jpeg)
![screenshot_2017-05-18-08-44-30 1](https://cloud.githubusercontent.com/assets/12256227/26182081/f1206634-3ba7-11e7-8e26-a352d34c45d6.jpeg)
![screenshot_2017-05-18-08-44-52 1](https://cloud.githubusercontent.com/assets/12256227/26182090/f82ce858-3ba7-11e7-8a9e-ed576ffb14c0.jpeg)
![screenshot_2017-05-18-08-44-58 1](https://cloud.githubusercontent.com/assets/12256227/26182095/ffc60874-3ba7-11e7-8ec4-b032ef6721c0.jpeg)

运行的是github上download下来的demo：app-release.apk
机型是  华为  Android 4.2.2
使用 三星 Android 5.0 测试结果一样

**Comment by addappcn** [comment]
fix  #1 ，请更新，谢谢。
