### ISSUE TITLE
setRangeStart初始值会出现一瞬间的动画切换

### ISSUE THREAD

**Issue by MYLJL** [addappcn/android-pickers#34]
比如 设置 setRangeStart（0,0）  选中的颜色是红色，但刚进入页面时字体是黑色并且置顶的，0.3秒后跳到选中

**Comment by addappcn** [comment]
这个是要有一个切换效果，正常的 ，我看看能优化下不

**Comment by addappcn** [comment]
您有空看看问题还存在不  不存在你就关了
