### ISSUE TITLE
DateTimePicker的setDateRangeStart方法有bug

### ISSUE THREAD

**Issue by beiguancyc** [addappcn/android-pickers#39]
比如设置setDateRangeStart的时间为2019-07-10 00：00，如果反复不停的弹出关闭测试，则有很大几率日期会变成2019-09-12 02:02，滚轮向后滚动了两格。未跟踪代码，个人猜测是滚轮没来得及复位所致。

几乎开关5次即可复现一次

**Comment by addappcn** [comment]
现在应该不会了 ，请看下demo  ，我先关闭了，有问题再提出来。
