### ISSUE TITLE
请问能够这样实现么

### ISSUE THREAD

**Issue by JokeZhang** [addappcn/android-pickers#4]
数组为：`[
{name:'王麻子',id:'1'},
{name:'张三',id:'2'},
{name:'李四',id:'3'}
]`
然后我之能够指定item显示的项比如item.name 或者item[index].name像地址选择器那样

**Comment by addappcn** [comment]
如果数据是对象就自己改对应的picker吧  目前不支持对象   因为你传对象  对应的picker获取不到你要显示的数据   目前只能自己修改代码
